# Generated by Django 5.1.4 on 2024-12-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                ("discussion_id", models.AutoField(primary_key=True, serialize=False)),
                ("author_id", models.IntegerField()),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("parent_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("teacher_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Viewer",
            fields=[
                ("viewer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("inquiry", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("gallery_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("image_file", models.ImageField(upload_to="gallery/")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.admin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("student_class", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                (
                    "identity_card",
                    models.FileField(blank=True, upload_to="identity_cards/"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="main.parent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("billing_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.admin"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billings",
                        to="main.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                ("report_card_id", models.AutoField(primary_key=True, serialize=False)),
                ("term", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
                ("grade", models.CharField(max_length=5)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="main.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryNote",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("content", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_notes",
                        to="main.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassRoutine",
            fields=[
                ("routine_id", models.AutoField(primary_key=True, serialize=False)),
                ("student_class", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=10)),
                ("routine_file", models.FileField(upload_to="routines/")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "registration_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("child_name", models.CharField(max_length=100)),
                ("student_class", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="main.viewer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("inquiry_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="main.viewer",
                    ),
                ),
            ],
        ),
    ]
